package cn.com.entity;

public class Game {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.ID
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.GAME_NAME
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private String gameName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.PINYIN
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.STATE
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.COMPANY
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.GAME_INDEX
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private String gameIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.GAME_HOT
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private Integer gameHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.GAME_NUM
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private String gameNum;

    @Override
    public String toString() {
        return "Game{" +
                "id=" + id +
                ", gameName='" + gameName + '\'' +
                ", pinyin='" + pinyin + '\'' +
                ", state=" + state +
                ", company='" + company + '\'' +
                ", gameIndex='" + gameIndex + '\'' +
                ", gameHot=" + gameHot +
                ", gameNum='" + gameNum + '\'' +
                ", orderIndex=" + orderIndex +
                ", picUrl='" + picUrl + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.ORDER_INDEX
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private Integer orderIndex;
    private  String picUrl;

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.ID
     *
     * @return the value of game.ID
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.ID
     *
     * @param id the value for game.ID
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.GAME_NAME
     *
     * @return the value of game.GAME_NAME
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.GAME_NAME
     *
     * @param gameName the value for game.GAME_NAME
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setGameName(String gameName) {
        this.gameName = gameName == null ? null : gameName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.PINYIN
     *
     * @return the value of game.PINYIN
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.PINYIN
     *
     * @param pinyin the value for game.PINYIN
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.STATE
     *
     * @return the value of game.STATE
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.STATE
     *
     * @param state the value for game.STATE
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.COMPANY
     *
     * @return the value of game.COMPANY
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.COMPANY
     *
     * @param company the value for game.COMPANY
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.GAME_INDEX
     *
     * @return the value of game.GAME_INDEX
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public String getGameIndex() {
        return gameIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.GAME_INDEX
     *
     * @param gameIndex the value for game.GAME_INDEX
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setGameIndex(String gameIndex) {
        this.gameIndex = gameIndex == null ? null : gameIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.GAME_HOT
     *
     * @return the value of game.GAME_HOT
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public Integer getGameHot() {
        return gameHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.GAME_HOT
     *
     * @param gameHot the value for game.GAME_HOT
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setGameHot(Integer gameHot) {
        this.gameHot = gameHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.GAME_NUM
     *
     * @return the value of game.GAME_NUM
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public String getGameNum() {
        return gameNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.GAME_NUM
     *
     * @param gameNum the value for game.GAME_NUM
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setGameNum(String gameNum) {
        this.gameNum = gameNum == null ? null : gameNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.ORDER_INDEX
     *
     * @return the value of game.ORDER_INDEX
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.ORDER_INDEX
     *
     * @param orderIndex the value for game.ORDER_INDEX
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }
}