package cn.com.entity;

public class GameArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_area.ID
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_area.GAME_ID
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private Long gameId;

    @Override
    public String toString() {
        return "GameArea{" +
                "id=" + id +
                ", gameId=" + gameId +
                ", areaName='" + areaName + '\'' +
                ", state=" + state +
                ", game=" + game +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_area.AREA_NAME
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_area.STATE
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    private Integer state;

    private  Game game;

    public Game getGame() {
        return game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_area.ID
     *
     * @return the value of game_area.ID
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_area.ID
     *
     * @param id the value for game_area.ID
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_area.GAME_ID
     *
     * @return the value of game_area.GAME_ID
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public Long getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_area.GAME_ID
     *
     * @param gameId the value for game_area.GAME_ID
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_area.AREA_NAME
     *
     * @return the value of game_area.AREA_NAME
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_area.AREA_NAME
     *
     * @param areaName the value for game_area.AREA_NAME
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_area.STATE
     *
     * @return the value of game_area.STATE
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_area.STATE
     *
     * @param state the value for game_area.STATE
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

}