package cn.com.entity;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_id
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private Long messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_title
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private String messageTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_content
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_state
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private String messageState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_type
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.user_id
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_id
     *
     * @return the value of message.message_id
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_id
     *
     * @param messageId the value for message.message_id
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_title
     *
     * @return the value of message.message_title
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public String getMessageTitle() {
        return messageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_title
     *
     * @param messageTitle the value for message.message_title
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle == null ? null : messageTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_content
     *
     * @return the value of message.message_content
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_content
     *
     * @param messageContent the value for message.message_content
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_state
     *
     * @return the value of message.message_state
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public String getMessageState() {
        return messageState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_state
     *
     * @param messageState the value for message.message_state
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setMessageState(String messageState) {
        this.messageState = messageState == null ? null : messageState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_type
     *
     * @return the value of message.message_type
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_type
     *
     * @param messageType the value for message.message_type
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType == null ? null : messageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_id
     *
     * @return the value of message.user_id
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.user_id
     *
     * @param userId the value for message.user_id
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "Message{" +
                "messageId=" + messageId +
                ", messageTitle='" + messageTitle + '\'' +
                ", messageContent='" + messageContent + '\'' +
                ", createTime=" + createTime +
                ", messageState='" + messageState + '\'' +
                ", messageType='" + messageType + '\'' +
                ", userId=" + userId +
                '}';
    }
}