package cn.com.entity;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_id
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private Long noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_title
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private String noticeTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_content
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private String noticeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.create_time
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_id
     *
     * @return the value of notice.notice_id
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public Long getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_id
     *
     * @param noticeId the value for notice.notice_id
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setNoticeId(Long noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_title
     *
     * @return the value of notice.notice_title
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public String getNoticeTitle() {
        return noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_title
     *
     * @param noticeTitle the value for notice.notice_title
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle == null ? null : noticeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_content
     *
     * @return the value of notice.notice_content
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_content
     *
     * @param noticeContent the value for notice.notice_content
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent == null ? null : noticeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.create_time
     *
     * @return the value of notice.create_time
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.create_time
     *
     * @param createTime the value for notice.create_time
     *
     * @mbggenerated Sat Apr 14 12:22:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "Notice{" +
                "noticeId=" + noticeId +
                ", noticeTitle='" + noticeTitle + '\'' +
                ", noticeContent='" + noticeContent + '\'' +
                ", createTime=" + createTime +
                '}';
    }
}