package cn.com.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ProductVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private Long productId;

    private Game game;

    private GameArea gameArea;

    private User user;

    public Game getGame() {
        return game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    public GameArea getGameArea() {
        return gameArea;
    }

    public void setGameArea(GameArea gameArea) {
        this.gameArea = gameArea;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.producer_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private Integer producerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.game_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private Long gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.area_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.account
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.account_role_name
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String accountRoleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.account_password
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String accountPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.account_question
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String accountQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.account_anwser
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String accountAnwser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.account_level
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String accountLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_price
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_state
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String productState;

    private String productStateName;

    @Override
    public String toString() {
        return "ProductVo{" +
                "productId=" + productId +
                ", game=" + game +
                ", gameArea=" + gameArea +
                ", user=" + user +
                ", producerId=" + producerId +
                ", gameId=" + gameId +
                ", areaId=" + areaId +
                ", account='" + account + '\'' +
                ", accountRoleName='" + accountRoleName + '\'' +
                ", accountPassword='" + accountPassword + '\'' +
                ", accountQuestion='" + accountQuestion + '\'' +
                ", accountAnwser='" + accountAnwser + '\'' +
                ", accountLevel='" + accountLevel + '\'' +
                ", productName='" + productName + '\'' +
                ", productPrice=" + productPrice +
                ", productState='" + productState + '\'' +
                ", productStateName='" + productStateName + '\'' +
                ", productPicurl='" + productPicurl + '\'' +
                ", comment='" + comment + '\'' +
                ", accountPhone='" + accountPhone + '\'' +
                ", accountEmail='" + accountEmail + '\'' +
                ", accountBand='" + accountBand + '\'' +
                ", createTime=" + createTime +
                '}';
    }

    public String getProductStateName() {
        return productStateName;
    }

    public void setProductStateName(String productStateName) {
        this.productStateName = productStateName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_picurl
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String productPicurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.comment
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.account_phone
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String accountPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.account_email
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String accountEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.account_band
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private String accountBand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.producer_id
     *
     * @return the value of product.producer_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public Integer getProducerId() {
        return producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.producer_id
     *
     * @param producerId the value for product.producer_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.game_id
     *
     * @return the value of product.game_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public Long getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.game_id
     *
     * @param gameId the value for product.game_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.area_id
     *
     * @return the value of product.area_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.area_id
     *
     * @param areaId the value for product.area_id
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.account
     *
     * @return the value of product.account
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.account
     *
     * @param account the value for product.account
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.account_role_name
     *
     * @return the value of product.account_role_name
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getAccountRoleName() {
        return accountRoleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.account_role_name
     *
     * @param accountRoleName the value for product.account_role_name
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAccountRoleName(String accountRoleName) {
        this.accountRoleName = accountRoleName == null ? null : accountRoleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.account_password
     *
     * @return the value of product.account_password
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.account_password
     *
     * @param accountPassword the value for product.account_password
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword == null ? null : accountPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.account_question
     *
     * @return the value of product.account_question
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getAccountQuestion() {
        return accountQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.account_question
     *
     * @param accountQuestion the value for product.account_question
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAccountQuestion(String accountQuestion) {
        this.accountQuestion = accountQuestion == null ? null : accountQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.account_anwser
     *
     * @return the value of product.account_anwser
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getAccountAnwser() {
        return accountAnwser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.account_anwser
     *
     * @param accountAnwser the value for product.account_anwser
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAccountAnwser(String accountAnwser) {
        this.accountAnwser = accountAnwser == null ? null : accountAnwser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.account_level
     *
     * @return the value of product.account_level
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getAccountLevel() {
        return accountLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.account_level
     *
     * @param accountLevel the value for product.account_level
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAccountLevel(String accountLevel) {
        this.accountLevel = accountLevel == null ? null : accountLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_price
     *
     * @return the value of product.product_price
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_price
     *
     * @param productPrice the value for product.product_price
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_state
     *
     * @return the value of product.product_state
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getProductState() {
        return productState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_state
     *
     * @param productState the value for product.product_state
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setProductState(String productState) {
        this.productState = productState == null ? null : productState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_picurl
     *
     * @return the value of product.product_picurl
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getProductPicurl() {
        return productPicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_picurl
     *
     * @param productPicurl the value for product.product_picurl
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setProductPicurl(String productPicurl) {
        this.productPicurl = productPicurl == null ? null : productPicurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.comment
     *
     * @return the value of product.comment
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.comment
     *
     * @param comment the value for product.comment
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.account_phone
     *
     * @return the value of product.account_phone
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getAccountPhone() {
        return accountPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.account_phone
     *
     * @param accountPhone the value for product.account_phone
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAccountPhone(String accountPhone) {
        this.accountPhone = accountPhone == null ? null : accountPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.account_email
     *
     * @return the value of product.account_email
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getAccountEmail() {
        return accountEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.account_email
     *
     * @param accountEmail the value for product.account_email
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAccountEmail(String accountEmail) {
        this.accountEmail = accountEmail == null ? null : accountEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.account_band
     *
     * @return the value of product.account_band
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getAccountBand() {
        return accountBand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.account_band
     *
     * @param accountBand the value for product.account_band
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setAccountBand(String accountBand) {
        this.accountBand = accountBand == null ? null : accountBand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}