package cn.com.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProducerIdIsNull() {
            addCriterion("producer_id is null");
            return (Criteria) this;
        }

        public Criteria andProducerIdIsNotNull() {
            addCriterion("producer_id is not null");
            return (Criteria) this;
        }

        public Criteria andProducerIdEqualTo(Integer value) {
            addCriterion("producer_id =", value, "producerId");
            return (Criteria) this;
        }

        public Criteria andProducerIdNotEqualTo(Integer value) {
            addCriterion("producer_id <>", value, "producerId");
            return (Criteria) this;
        }

        public Criteria andProducerIdGreaterThan(Integer value) {
            addCriterion("producer_id >", value, "producerId");
            return (Criteria) this;
        }

        public Criteria andProducerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("producer_id >=", value, "producerId");
            return (Criteria) this;
        }

        public Criteria andProducerIdLessThan(Integer value) {
            addCriterion("producer_id <", value, "producerId");
            return (Criteria) this;
        }

        public Criteria andProducerIdLessThanOrEqualTo(Integer value) {
            addCriterion("producer_id <=", value, "producerId");
            return (Criteria) this;
        }

        public Criteria andProducerIdIn(List<Integer> values) {
            addCriterion("producer_id in", values, "producerId");
            return (Criteria) this;
        }

        public Criteria andProducerIdNotIn(List<Integer> values) {
            addCriterion("producer_id not in", values, "producerId");
            return (Criteria) this;
        }

        public Criteria andProducerIdBetween(Integer value1, Integer value2) {
            addCriterion("producer_id between", value1, value2, "producerId");
            return (Criteria) this;
        }

        public Criteria andProducerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("producer_id not between", value1, value2, "producerId");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNull() {
            addCriterion("game_id is null");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNotNull() {
            addCriterion("game_id is not null");
            return (Criteria) this;
        }

        public Criteria andGameIdEqualTo(Long value) {
            addCriterion("game_id =", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotEqualTo(Long value) {
            addCriterion("game_id <>", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdGreaterThan(Long value) {
            addCriterion("game_id >", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdGreaterThanOrEqualTo(Long value) {
            addCriterion("game_id >=", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdLessThan(Long value) {
            addCriterion("game_id <", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdLessThanOrEqualTo(Long value) {
            addCriterion("game_id <=", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdIn(List<Long> values) {
            addCriterion("game_id in", values, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotIn(List<Long> values) {
            addCriterion("game_id not in", values, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdBetween(Long value1, Long value2) {
            addCriterion("game_id between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotBetween(Long value1, Long value2) {
            addCriterion("game_id not between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(Long value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(Long value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(Long value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(Long value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(Long value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<Long> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<Long> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(Long value1, Long value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(Long value1, Long value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameIsNull() {
            addCriterion("account_role_name is null");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameIsNotNull() {
            addCriterion("account_role_name is not null");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameEqualTo(String value) {
            addCriterion("account_role_name =", value, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameNotEqualTo(String value) {
            addCriterion("account_role_name <>", value, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameGreaterThan(String value) {
            addCriterion("account_role_name >", value, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("account_role_name >=", value, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameLessThan(String value) {
            addCriterion("account_role_name <", value, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameLessThanOrEqualTo(String value) {
            addCriterion("account_role_name <=", value, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameLike(String value) {
            addCriterion("account_role_name like", value, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameNotLike(String value) {
            addCriterion("account_role_name not like", value, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameIn(List<String> values) {
            addCriterion("account_role_name in", values, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameNotIn(List<String> values) {
            addCriterion("account_role_name not in", values, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameBetween(String value1, String value2) {
            addCriterion("account_role_name between", value1, value2, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountRoleNameNotBetween(String value1, String value2) {
            addCriterion("account_role_name not between", value1, value2, "accountRoleName");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordIsNull() {
            addCriterion("account_password is null");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordIsNotNull() {
            addCriterion("account_password is not null");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordEqualTo(String value) {
            addCriterion("account_password =", value, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordNotEqualTo(String value) {
            addCriterion("account_password <>", value, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordGreaterThan(String value) {
            addCriterion("account_password >", value, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("account_password >=", value, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordLessThan(String value) {
            addCriterion("account_password <", value, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordLessThanOrEqualTo(String value) {
            addCriterion("account_password <=", value, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordLike(String value) {
            addCriterion("account_password like", value, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordNotLike(String value) {
            addCriterion("account_password not like", value, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordIn(List<String> values) {
            addCriterion("account_password in", values, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordNotIn(List<String> values) {
            addCriterion("account_password not in", values, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordBetween(String value1, String value2) {
            addCriterion("account_password between", value1, value2, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountPasswordNotBetween(String value1, String value2) {
            addCriterion("account_password not between", value1, value2, "accountPassword");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionIsNull() {
            addCriterion("account_question is null");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionIsNotNull() {
            addCriterion("account_question is not null");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionEqualTo(String value) {
            addCriterion("account_question =", value, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionNotEqualTo(String value) {
            addCriterion("account_question <>", value, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionGreaterThan(String value) {
            addCriterion("account_question >", value, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionGreaterThanOrEqualTo(String value) {
            addCriterion("account_question >=", value, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionLessThan(String value) {
            addCriterion("account_question <", value, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionLessThanOrEqualTo(String value) {
            addCriterion("account_question <=", value, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionLike(String value) {
            addCriterion("account_question like", value, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionNotLike(String value) {
            addCriterion("account_question not like", value, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionIn(List<String> values) {
            addCriterion("account_question in", values, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionNotIn(List<String> values) {
            addCriterion("account_question not in", values, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionBetween(String value1, String value2) {
            addCriterion("account_question between", value1, value2, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountQuestionNotBetween(String value1, String value2) {
            addCriterion("account_question not between", value1, value2, "accountQuestion");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserIsNull() {
            addCriterion("account_anwser is null");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserIsNotNull() {
            addCriterion("account_anwser is not null");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserEqualTo(String value) {
            addCriterion("account_anwser =", value, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserNotEqualTo(String value) {
            addCriterion("account_anwser <>", value, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserGreaterThan(String value) {
            addCriterion("account_anwser >", value, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserGreaterThanOrEqualTo(String value) {
            addCriterion("account_anwser >=", value, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserLessThan(String value) {
            addCriterion("account_anwser <", value, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserLessThanOrEqualTo(String value) {
            addCriterion("account_anwser <=", value, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserLike(String value) {
            addCriterion("account_anwser like", value, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserNotLike(String value) {
            addCriterion("account_anwser not like", value, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserIn(List<String> values) {
            addCriterion("account_anwser in", values, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserNotIn(List<String> values) {
            addCriterion("account_anwser not in", values, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserBetween(String value1, String value2) {
            addCriterion("account_anwser between", value1, value2, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountAnwserNotBetween(String value1, String value2) {
            addCriterion("account_anwser not between", value1, value2, "accountAnwser");
            return (Criteria) this;
        }

        public Criteria andAccountLevelIsNull() {
            addCriterion("account_level is null");
            return (Criteria) this;
        }

        public Criteria andAccountLevelIsNotNull() {
            addCriterion("account_level is not null");
            return (Criteria) this;
        }

        public Criteria andAccountLevelEqualTo(String value) {
            addCriterion("account_level =", value, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelNotEqualTo(String value) {
            addCriterion("account_level <>", value, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelGreaterThan(String value) {
            addCriterion("account_level >", value, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelGreaterThanOrEqualTo(String value) {
            addCriterion("account_level >=", value, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelLessThan(String value) {
            addCriterion("account_level <", value, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelLessThanOrEqualTo(String value) {
            addCriterion("account_level <=", value, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelLike(String value) {
            addCriterion("account_level like", value, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelNotLike(String value) {
            addCriterion("account_level not like", value, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelIn(List<String> values) {
            addCriterion("account_level in", values, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelNotIn(List<String> values) {
            addCriterion("account_level not in", values, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelBetween(String value1, String value2) {
            addCriterion("account_level between", value1, value2, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andAccountLevelNotBetween(String value1, String value2) {
            addCriterion("account_level not between", value1, value2, "accountLevel");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNull() {
            addCriterion("product_price is null");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNotNull() {
            addCriterion("product_price is not null");
            return (Criteria) this;
        }

        public Criteria andProductPriceEqualTo(BigDecimal value) {
            addCriterion("product_price =", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotEqualTo(BigDecimal value) {
            addCriterion("product_price <>", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThan(BigDecimal value) {
            addCriterion("product_price >", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("product_price >=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThan(BigDecimal value) {
            addCriterion("product_price <", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("product_price <=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceIn(List<BigDecimal> values) {
            addCriterion("product_price in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotIn(List<BigDecimal> values) {
            addCriterion("product_price not in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_price between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_price not between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductStateIsNull() {
            addCriterion("product_state is null");
            return (Criteria) this;
        }

        public Criteria andProductStateIsNotNull() {
            addCriterion("product_state is not null");
            return (Criteria) this;
        }

        public Criteria andProductStateEqualTo(String value) {
            addCriterion("product_state =", value, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateNotEqualTo(String value) {
            addCriterion("product_state <>", value, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateGreaterThan(String value) {
            addCriterion("product_state >", value, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateGreaterThanOrEqualTo(String value) {
            addCriterion("product_state >=", value, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateLessThan(String value) {
            addCriterion("product_state <", value, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateLessThanOrEqualTo(String value) {
            addCriterion("product_state <=", value, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateLike(String value) {
            addCriterion("product_state like", value, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateNotLike(String value) {
            addCriterion("product_state not like", value, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateIn(List<String> values) {
            addCriterion("product_state in", values, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateNotIn(List<String> values) {
            addCriterion("product_state not in", values, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateBetween(String value1, String value2) {
            addCriterion("product_state between", value1, value2, "productState");
            return (Criteria) this;
        }

        public Criteria andProductStateNotBetween(String value1, String value2) {
            addCriterion("product_state not between", value1, value2, "productState");
            return (Criteria) this;
        }

        public Criteria andProductPicurlIsNull() {
            addCriterion("product_picurl is null");
            return (Criteria) this;
        }

        public Criteria andProductPicurlIsNotNull() {
            addCriterion("product_picurl is not null");
            return (Criteria) this;
        }

        public Criteria andProductPicurlEqualTo(String value) {
            addCriterion("product_picurl =", value, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlNotEqualTo(String value) {
            addCriterion("product_picurl <>", value, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlGreaterThan(String value) {
            addCriterion("product_picurl >", value, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlGreaterThanOrEqualTo(String value) {
            addCriterion("product_picurl >=", value, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlLessThan(String value) {
            addCriterion("product_picurl <", value, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlLessThanOrEqualTo(String value) {
            addCriterion("product_picurl <=", value, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlLike(String value) {
            addCriterion("product_picurl like", value, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlNotLike(String value) {
            addCriterion("product_picurl not like", value, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlIn(List<String> values) {
            addCriterion("product_picurl in", values, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlNotIn(List<String> values) {
            addCriterion("product_picurl not in", values, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlBetween(String value1, String value2) {
            addCriterion("product_picurl between", value1, value2, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andProductPicurlNotBetween(String value1, String value2) {
            addCriterion("product_picurl not between", value1, value2, "productPicurl");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneIsNull() {
            addCriterion("account_phone is null");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneIsNotNull() {
            addCriterion("account_phone is not null");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneEqualTo(String value) {
            addCriterion("account_phone =", value, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneNotEqualTo(String value) {
            addCriterion("account_phone <>", value, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneGreaterThan(String value) {
            addCriterion("account_phone >", value, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("account_phone >=", value, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneLessThan(String value) {
            addCriterion("account_phone <", value, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneLessThanOrEqualTo(String value) {
            addCriterion("account_phone <=", value, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneLike(String value) {
            addCriterion("account_phone like", value, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneNotLike(String value) {
            addCriterion("account_phone not like", value, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneIn(List<String> values) {
            addCriterion("account_phone in", values, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneNotIn(List<String> values) {
            addCriterion("account_phone not in", values, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneBetween(String value1, String value2) {
            addCriterion("account_phone between", value1, value2, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountPhoneNotBetween(String value1, String value2) {
            addCriterion("account_phone not between", value1, value2, "accountPhone");
            return (Criteria) this;
        }

        public Criteria andAccountEmailIsNull() {
            addCriterion("account_email is null");
            return (Criteria) this;
        }

        public Criteria andAccountEmailIsNotNull() {
            addCriterion("account_email is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEmailEqualTo(String value) {
            addCriterion("account_email =", value, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailNotEqualTo(String value) {
            addCriterion("account_email <>", value, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailGreaterThan(String value) {
            addCriterion("account_email >", value, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailGreaterThanOrEqualTo(String value) {
            addCriterion("account_email >=", value, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailLessThan(String value) {
            addCriterion("account_email <", value, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailLessThanOrEqualTo(String value) {
            addCriterion("account_email <=", value, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailLike(String value) {
            addCriterion("account_email like", value, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailNotLike(String value) {
            addCriterion("account_email not like", value, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailIn(List<String> values) {
            addCriterion("account_email in", values, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailNotIn(List<String> values) {
            addCriterion("account_email not in", values, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailBetween(String value1, String value2) {
            addCriterion("account_email between", value1, value2, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountEmailNotBetween(String value1, String value2) {
            addCriterion("account_email not between", value1, value2, "accountEmail");
            return (Criteria) this;
        }

        public Criteria andAccountBandIsNull() {
            addCriterion("account_band is null");
            return (Criteria) this;
        }

        public Criteria andAccountBandIsNotNull() {
            addCriterion("account_band is not null");
            return (Criteria) this;
        }

        public Criteria andAccountBandEqualTo(String value) {
            addCriterion("account_band =", value, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandNotEqualTo(String value) {
            addCriterion("account_band <>", value, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandGreaterThan(String value) {
            addCriterion("account_band >", value, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandGreaterThanOrEqualTo(String value) {
            addCriterion("account_band >=", value, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandLessThan(String value) {
            addCriterion("account_band <", value, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandLessThanOrEqualTo(String value) {
            addCriterion("account_band <=", value, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandLike(String value) {
            addCriterion("account_band like", value, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandNotLike(String value) {
            addCriterion("account_band not like", value, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandIn(List<String> values) {
            addCriterion("account_band in", values, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandNotIn(List<String> values) {
            addCriterion("account_band not in", values, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandBetween(String value1, String value2) {
            addCriterion("account_band between", value1, value2, "accountBand");
            return (Criteria) this;
        }

        public Criteria andAccountBandNotBetween(String value1, String value2) {
            addCriterion("account_band not between", value1, value2, "accountBand");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 15 14:52:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}