package cn.com.dao;

import cn.com.entity.Game;
import org.springframework.stereotype.Repository;


import java.util.List;
@Repository
public interface GameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int insert(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int insertSelective(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    Game selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int updateByPrimaryKeySelective(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int updateByPrimaryKey(Game record);


    List<Game> selectAllGame();
    List<Game> selectStateGame();
    List<Game> selectAllGameBySearch(String search);
    List<Game> selectHotGame();
}