package cn.com.dao;

import cn.com.entity.GameArea;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface GameAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int insert(GameArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int insertSelective(GameArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    GameArea selectByPrimaryKey(Long id);
    List<GameArea> selectAllGameArea();
    List<GameArea> selectGameAreaByGameId(Long id);
    List<GameArea> selectGameStateAreaByGameId(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int updateByPrimaryKeySelective(GameArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_area
     *
     * @mbggenerated Wed Mar 14 11:06:44 CST 2018
     */
    int updateByPrimaryKey(GameArea record);
}