package cn.com.dao;

import cn.com.entity.Product;
import cn.com.entity.ProductExample;
import java.util.List;

import cn.com.entity.ProductVo;
import org.apache.ibatis.annotations.Param;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    int countByExample(ProductExample example);

    int todayProduct();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    List<Product> selectByExample(ProductExample example);
    List<ProductVo> selectProductVo();
    List<ProductVo> selectProductVoBySearch(String search);
    List<ProductVo> selectProductVoByidstate(Product product);
    ProductVo selectProductVoByProductId(Long productId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    Product selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Apr 15 14:52:09 CST 2018
     */
    int updateByPrimaryKey(Product record);
}